### ISSUE TITLE
Forms - Potentially no form action

### ISSUE THREAD

**Issue by DeanmvSG** [mdyd-dev/posify#25]
https://github.com/mdyd-dev/posify/blob/e5e402edbdb87721408925c2b03e7937012639a7/src/lib/replace-urls/form.js#L4

Some forms from platforms (BC!) don't use a form action but instead and `onsubmit` and then JS. I've updated this function to handle finding forms with an `onsubmit` as well and then remove the `onsubmit` after:

```
const forms = document.querySelectorAll('form[action]') || document.querySelectorAll('form[onsubmit]');
	forms.forEach(el => {
		el.action = '/__form';
		el.removeAttribute('onsubmit');
	});
```

**Comment by pavelloz** [comment]
Yes, i noticed that originally, but onsubmit also often had some useful field validations so that was a concious decision :)

Nonetheless, ill change the code so it will handle that case too :)
