### ISSUE TITLE
CSS imports being stripped

### ISSUE THREAD

**Issue by DeanmvSG** [mdyd-dev/posify#26]
https://github.com/mdyd-dev/posify/blob/e5e402edbdb87721408925c2b03e7937012639a7/src/commands/optimize/css.js#L11

CSS imports such as:
`@import url("base.css");`

Would get stripped by CleanCSS.  Using the flag `{ inline: false }` leaves those lines intact so that the end site looks the same as source site

Inlining options -> https://github.com/jakubpawlowicz/clean-css#inlining-options

**Comment by pavelloz** [comment]
Stripped? Not inlined as the name suggests?
