### ISSUE TITLE
zsh autocomplete ?

### ISSUE THREAD

**Issue by Developer-DNM** [mdyd-dev/posify#27]
Would be cool to have autocomplete (plugin is there :) )

**Comment by Developer-DNM** [comment]
https://github.com/oclif/plugin-autocomplete

**Comment by pavelloz** [comment]
Ok, this is far too much work both for me and every user that would have to install those autocompletions, AND it will not autocomplete parameters. Too much work to add something mediocre and easy to skip by most users.
